### ISSUE TITLE
Multiple Tags Using TDoA

### ISSUE THREAD

**Issue by HardX18** [bitcraze/libdw1000#24] opened 2024-04-11 17:15 UTC
Is it possible to have use multiple tags using this library and perform TDoA ??

**Comment by ataffanel** [comment] 2024-04-12 07:51
This is better talked about in a discussions since it is a question. Closing as duplicate of discussion https://github.com/orgs/bitcraze/discussions/1279.

**Closed by ataffanel** 2024-04-12 07:51 UTC
